### PR TITLE
Add Projects to .NET Framework samples that use NuGet

### PR DESCRIPTION
**Pull request by datalogics-robb**
Add Projects to .NET Framework samples that use NuGet - these projects will run out of the box with the next release of APDFL.

### CODE REVIEW

**Review by datalogics-saharay — COMMENTED** [review]
@datalogics-robb The changes look good to me! I have a few questions regarding testing these changes:

- What's the best way to test and run the samples with these changes?
- I see that the PackageReference refers to the LM NuGet package but would I have to install the package manually to run the sample?

**Comment by datalogics-robb** [comment]
> What's the best way to test and run the samples with these changes?

Open up one of the solutions in visual studio 2019, and build it.  The way the projects are set up, they will pull down the latest NuGet .NET Framework packages from nuget.org - the as-of-yet-unreleased latest version will activate automatically when a sample runs - but for now you can give a sample a key when prompted.

**Review by datalogics-saharay — DISMISSED** [review]
@datalogics-robb I ran all the samples locally by downloading this branch as a zip file, and I have found a few issues that I will split into 4 categories.

### **These samples produce a missing references error when run:**
- AddElements
- PrintPDFGUI
- PrintToPlotter
- DisplayPDF
- DotNETViewer
- DotNetViewerComponent
- PDFObjectExplorer
- DrawSeparations
- DrawToBitmap
- GetSeparatedImages
- ImagesEmbedICCProfile
- RasterizePage
- ImageResampling
- ImageFromStream
- ImageExtraction

### **These samples don't have .csproj and .sln files, so customers will not be able to run them:**

- Action
- AddCollection
- ChangeLayerConfiguration
- CreateLayer
- PageLabels
- PageObject
- ColorConvertDocument
- FacturXConverter
- PDFAConverter
- PDFXConverter
- ZugferdConverter
- MemoryFileSystem
- WebApplication
- AddGlyphs

### **This sample throws an error saying the input file is not found when the sample is run:**

- MergePDF

### **These samples throw an error saying ExtractText.cs is not found:**

- ExtractAcroFormFieldData
- ExtractTextByRegion
- ExtractTextFromAnnotations
- ExtractTextFromMultiRegions
- ExtractTextPerservingStyleAndPositionInfo

**Review by datalogics-saharay — COMMENTED** [review]
The changes look good, and I tested the samples that were having issues. The following samples have the issues mentioned below:

### **Unhandled exception when run:**
- DisplayPDF

### **Unable to run sample due to missing .sln file:**

- RasterizePage
- Action
- AddCollection
- ChangeLayerConfiguration
- CreateLayer
- PageLabels
- PageObject
- ColorConvertDocument
- Factur-XConverter
- PDFAConverter
- PDFXConverter
- ZugferdConverter
- MemoryFileSystem
- AddGlyphs

### **Missing .csproj and .sln file**
- WebApplication

**Comment by datalogics-robb** [comment]
SLN files aren't necessary for each project, so I added a top-level SLN file that will build them all.
Project files were omitted for samples that are broken.

**Comment by datalogics-robb** [comment]
I removed DisplayPDF from the top-level solution file.

**Pull request merged**
